function generatePrompt() {
	randomIndex = Math.floor(Math.random() * propmt_list.length)
    return propmt_list[randomIndex]
}

module.exports = { generatePrompt }

propmt_list = [
	"What was the most peaceful moment during the day?",
	"Describe something you learned today that you didn't know before.",
	"Would you change any of the decisions you made today?",
	"How were your meals today? Do you feel nourished?",
	"What frightened you today?",
	"Who do you wish you had talked to today? How do they improve your life?",
	"Describe the moments of frustration you felt today. How would your day have changed if those moments were different?",
	"If you'd had another hour during the day, how would you have spent it?",
	"Did something (or someone) empower you today?",
	"Did you stop yourself from doing something you enjoy today? Why or why not?",
	"Reflect on how your body feels. Where are you storing your stress? What put it there?",
	"Who helped you the most today? Who did you help the most?",
	"Describe your day from another person's perspective. Is it different from yours?",
	"If you were in charge, what would you forbid immediately?",
	"What needs to change in your job for you to feel fulfilled?",
	"What is a hobby that you'd like to pick up.",
	"If you could relive any day of your life and change nothing, what day would you choose?",
	"How would you like your life to be different in a year? How would you like it to be the same?",
	"If you had to live in another country, where would you live?",
	"How could you change your life to become a hero to someone else?",
	"What was something you desperately wanted as a child? What do you desperately want now?",
	"If you could take any college course you wanted, what would you take?",
	"Describe your ideal weekend. What would it include? What wouldn't it include?",
	"Rewrite a conversation you've had in the way you wish it had gone.",
	"What would you do if you found a puppy in the street?",
	"What would you do with a million dollars if you had to spend it in one hour?",
	"What would you do if you needed to change your career or major?",
	"What would you do if you could suddenly read minds?",
	"What would you do if you were locked out of your house?",
	"What would you do if your loved one were accused of a crime?",
	"What would you do if you were stranded on a desert island with someone you dislike?",
	"What would do if you lost all your possessions? What would you replace? What wouldn't you replace?",
	"What would you do if you lost one of your senses? Which would be the most difficult one to lose?",
	"Write a note to a teacher who inspired you. How have you used their lessons in your current life?",
	"What would you say to a childhood bully if you could?",
	"Write a letter to your teenage self.",
	"Put yourself 20 years in the future. Write a letter to your future self with questions and predictions.",
	"Craft a breakup letter to a bad habit.",
	"Who was your first crush?",
	"Write a letter from someone else to you. What do you need to hear from them?",
	"Look at your last few text messages. Rewrite one of them into a longer letter as if you were in the eighteenth century.",
	"Write a letter to someone you've lost.",
	"What was your best age so far?",
	"Do you have a memory that should be happy, but instead makes you sad? What about the other way around?",
	"When is a time in your life that you felt successful?",
	"Think about your best friend in childhood. What did you like to do together?",
	"Think about a lesson your parents taught you either by doing something well or not doing it well.",
	"When in your life have you felt brave?",
	"What book made you fall in love with reading?",
	"How old were you when you first felt like an adult?",
	"Who do you trust most? Why?",
	"What are your strengths in relationships (kindness, empathy, etc.)?",
	"How do you draw strength from loved ones?",
	"What do you value most in relationships (trust, respect, sense of humor, etc.)?",
	"What three important things have you learned from previous relationships?",
	"What five traits do you value most in potential partners?",
	"How do you show compassion to others? How can you extend that same compassion to yourself?",
	"What are three things working well in your current relationship? What are three things that could be better?",
	"What boundaries could you set in your relationships to safeguard your own well-being?",
	"What do you most want your children (or future children) to learn from you?",
	"How can you better support and appreciate your loved ones?",
	"What does love mean to you? How do you recognize it in a relationship?",
	"List three things you'd like to tell a friend, family member, or partner.",
	"How do you use your personal strengths and abilities at work?",
	"How do your co-workers and supervisors recognize your strengths?",
	"How does work fulfill you? Does it leave you wanting more?",
	"What part of your workday do you most enjoy?",
	"What about your work feels real, necessary, or important to you?",
	"Do you see yourself in the same job in 10 years?",
	"What are your career ambitions?",
	"What can you do to improve your work performance?",
	"What does your work teach you? Does it offer continued opportunities for learning and growth?",
	"Does your work drain or overwhelm you? Why? Is this something you can change?",
	"What values do you consider most important in life (honesty, justice, altruism, loyalty, etc.)? How do your actions align with those values?",
	"What three changes can you make to live according to your personal values?",
	"What do you appreciate most about your personality? What aspects do you find harder to accept?",
	"Explore an opinion or two that you held in the past but have since questioned or changed. What led you to change that opinion?",
	"What aspects of your life are you most grateful for?",
	"How do you show yourself kindness and compassion each day?",
	"What place makes you feel most peaceful? Describe that place using all five senses.",
	"What are your favorite hobbies? Why?",
	"What parts of life surprised you most? What turned out the way you expected it would?",
	"What three things would you share with your teenage self? What three questions would you want to ask an older version of yourself?",
	"Do your goals truly reflect your desires? Or do they reflect what someone else (a parent, partner, friend, etc.) wants for you?",
	"What helps you stay focused and motivated when you feel discouraged?",
	"What do you look forward to most in the future?",
	"What do you most want to accomplish in life?",
	"What are five things you appreciate about yourself?",
	"What are three great things that happened yesterday?",
	"What are 30 things that bring you joy?",
	"What are you looking forward to right now? If you can't think of anything, what can you do to change that?",
	"What is one thing under $100 that has made your life easier?",
	"What are 10 things you're actively enjoying about life right now?",
	"Name the top three emotions you are feeling at the moment. What are the emotions you want to feel today?",
	"What is the one thing you would tell your teenage self if you could?",
	"What is your body craving at the moment?",
	"What are 10 questions you wish you had the answers to right now?",
	"What do you know to be true today that you didn't know a year ago?",
	"What are you scared of right now?",
	"What's not working in your life right now?",
	"Who is someone you miss? What do you miss about them? How do they make you feel?",
	"What would your ideal day look like? Where would you be, what would you be doing and who with?",
	"Describe your perfect home - where is it, what does it look like and who do you share it with?",
	"When you were younger, what did you want to be when you grew up and why?",
	"What do you need more of in your life?",
	"If failure wasn't possible, what would you be doing right now?",
	"If you only had one year left of life, what would you do?",
	"In another life, who would you want to be?",
	"What's something you wish others knew about you?",
	"Who is someone you admire? What qualities do you love about them?",
	"Who is someone you envy and why?",
	"What distracts you from what's truly important each day?",
	"If you decided right now that you had enough money, and that you would always have enough, what would you do with your life?",
	"When you picture yourself 10 years from now, what do you want to have achieved and experienced?",
	"Write 5 affirmations for when you are feeling low.",
	"What is the best book you have read recently?",
	"How have you grown this year?",
	"What are the most important life lessons you have learned?",
	"Having trouble sleeping? What's keeping you up?",
	"What is the last dream you remember?",
	"Name the three biggest priorities in your life right now.",
	"What are your biggest fears?",
	"Do you have a fear that is stopping you from achieving your goals?",
	"What would you do if you were granted three wishes?",
	"How about if you were given five wishes?",
	"Name three bad habits you would like to change.",
	"What was the last show you went to?",
	"Do you have a secret talent you are hiding?",
	"What is your biggest regret?",
	"Think about someone you really love. Who came to mind?",
	"What 5 things are you grateful for this week?",
	"Name the one thing you are most grateful for in your life at this moment.",
	"Which people in your life are you most grateful for.",
	"When were you last surprised?",
	"What is the most exhilarating thing that has happened to you this year?",
	"Name a challenge you have overcome and how it helped you to grow.",
	"How can you show gratitude more?",
	"What are 3 things that have happened to you which were difficult but you are now grateful for the experience?",
	"Keep a food tracker for the day.",
	"Make a meal planner. Head to our meal planning post for ideas.",
	"What is your favorite way to exercise?",
	"Did you make healthy choices today?",
	"Name one simple way you can take a step to be healthier.",
	"How can you make activity part of your normal routine?",
	"What is your favorite food?",
	"Are you feeling stressed?",
	"Keep a mood or habit tracker to help understand your mental health.",
	"Think about what triggers your stress, emotions, poor eating habits.",
	"What are your top 10 goals?",
	"What is your 1-year goal?",
	"What is your 5-year goal?",
	"What is your 10-year goal?",
	"If you could start life again, would you? What would you change?",
	"Who is someone that inspires you and why?",
	"Is there a hobby you would like to start?",
	"Name a skill you would love to learn.",
	"What kind of person do you aspire to be?",
	"What is your favorite childhood memory?",
	"Do you have an embarrassing moment that still makes you cringe?",
	"Which was your best birthday ever and why?",
	"What was a hobby you loved as a kid?",
	"What was your favorite toy?",
	"What is your best memory with some of the special people in your life?",
	"What is a memory that always makes you smile?",
	"Where is the place you would like to visit the most?",
	"What has been your best trip so far?",
	"Who is the person you would like to travel with the most and why?",
	"If you could go back in time, where would you go?",
	"How does seeing somewhere new make you feel?",
	"What is a food you would love to try from a different country?",
	"What is the worst vacation you have ever had/",
	"Name 10 places you would love to see.",
	"Do your current friendships and relationships bring joy to you?",
	"What is your biggest concern right now?",
	"Do you think you are a positive or negative person?",
	"What are your best qualities?",
	"Could you be a better friend?",
	"Could you be a better partner/wife/husband/mother/father/daughter or Son?",
	"What things change your mood from positive to negative?",
	"Do you have a morning routine? Can it be improved?",
	"How are you feeling today?",
	"What is something you want to achieve this year?",
	"Make plans for Spring.",
	"Make a plan for your dream garden.",
	"What summer plans do you have?",
	"How would you make a raining day amazing?",
	"What is a challenge you would like to overcome?",
	"Plan all the holidays you celebrate.",
	"How are you progressing with your year goals?",
	"Name a fear you would like to overcome.",
	"What are you grateful for in your life?",
	"What have been the best summer vacations you have had?",
	"If you went back to school, what would you study?",
	"What are 10 affirmations you could say daily?",
	"What are you looking forward to in August?",
	"If you are a parent, plan an amazing day with your kid/s.",
	"What is your favorite thing about Fall?",
	"Make plans for celebrating Halloween",
	"What was your all-time favorite Halloween costume?",
	"What food really puts you in the Fall mood?",
	"The year is nearly over, what are something you want to achieve before it ends?",
	"What is your favorite winter activity?",
	"Did you reach your goals? Why? Why not?",
	"What is a skill you would like to learn next year?",
	"Which character from a book would you most like to meet and why?",
	"What would you do if 300 mice had just gotten out of their cages in a pet shop where you worked?",
	"What would you do if you were locked inside your favorite department store overnight?",
	"What would you do if you woke up one morning to find yourself invisible? ",
	"What would you do if you were able to communicate with animals? ",
	"What would you do if you could travel into the future? ",
	"What would you do if you could travel into the past? ",
	"What would you do if someone just gave you $1 million? ",
	"What would you do it all the electricity in the world just stopped? ",
	"What would you do if you could travel free anyplace in the world? ",
	"What would you do if the dinner served to you in a fancy restaurant came with a fly in the mashed potatoes? ",
	"Describe the perfect day.  Put in as many details as you can.  Make it a possible day, not a 'dream day.' ",
	"Who is the person from history that you would most like to meet and talk to?  Why?  What would you like to ask? ",
	"Who is the person from literature that you would most like to meet and talk to?  Why?  What would you like to ask? ",
	"Tell about what triggers anger in you or someone else. ",
	"Invent a monster and describe it.  Tell where it lives, what it eats, and what it does. ",
	"What is your favorite kind of weather?  Why? ",
	"What is the best book you have ever read?  Why did you like it?  Did reading the book change you in any way?  What way? ",
	"Think about an incident that happened to you and exaggerate in the telling.  Make it into a tall tale. ",
	"If you could go back in time anywhere and 'anywhen,' where/when would you go and why? ",
	"What law would you like to see enacted which would help people?  How would it help? ",
	"What commercial on TV do you dislike beyond all others?  What about it is particularly annoying to you?",
	"Design some gadget, machine, building, or other creation that might enrich the future.  What does it look like? What does it do?  How does it function?  In what ways might it benefit people?",
	"What current fashion in clothing do you particularly like or dislike?  Explain.",
	"Convince someone why music or art or computers are important in your life.  Make them appreciate your viewpoint.",
	"If you had $100,000, how would you spend it?",
	"Be a building you know well.  Talk about your life and memories.",
	"You are to tell a person from a distant planet or from another era what pollution is.  Make that person understand what causes it and why it is bad.",
	"If you could do something that you never have done before, what would it be?  Why would you want to do it?",
	"What do you consider your greatest accomplishment to date and why?",
	"What is your hobby?  Why do you enjoy it?",
	"If you could go somewhere where you've never gone before, where would you go and why?",
	"What's, if anything, would you be willing to fight or even die for?  Explain your answer.",
	"If you could change one thing about the world, what would it be?  Why would you make this change?",
	"Is there a machine you feel you could not live without?  Explain.",
	"Did you ever stick up for someone? ",
	"Did you ever get lost in a strange town? ",
	"Were you ever locked in or out?  What did you do? ",
	"What was it like to spend your first night away from home? ",
	"What was it like to come back home after a long vacation? ",
	"Did you ever win or lose a contest?  Tell the story about what happened. ",
	"Did you ever know someone who had 'everything'? ",
	"Were you ever in a helicopter, limousine, racecar, hot-air balloon, submarine, or horse-drawn  carriage? ",
	"Were you ever accused of something that you didn't do?",
	"Were you ever given a responsibility that you couldn't handle?",
	"Were you ever in a fire, flood, tornado, or hurricane?",
	"Did you ever catch fireflies?  Crickets?  Frogs?  Snakes?",
	"Did you ever break an important promise?",
	"Did you ever meet a famous person?",
	"Did you ever turn someone in or tell on someone and feel bad about it later?",
	"What would you pack in your suitcase if you could not go home again? ",
	"If you could change one law, what law would it be and how would you change it? ",
	"How forgiving are you when a friend lets you down?  Explain.  Give an example. ",
	"If you could only speak twenty words for the rest of your life, what words would head your list and why? ",
	"Have you ever wished you were either older or younger?  What would you consider to be the benefits?  The problems?",
	"If you had three wishes, what would they be?  (Do not ask for three more wishes)",
	"What is something special and/or different about you?  Why do you think it is special or different? ",
	"How do you know someone loves you, even if he or she doesn't say it? ",
	"Name one thing you like about yourself and why you like it. ",
	"Imagine yourself as a teacher.  What type of student would you like to teach and why?",
	"If you could be a character in any book, TV show, or movie, who would you be and why? ",
	"If you had to work in any store at your favorite mall,  which store would it be and why? ",
	"Who is the most important role model in your life?",
	"If you could study one subject in school that wasn't offered, what would it be and why?",
	"If you had a chance to live anywhere you could, where would it be and why?",
	"Is the school year too long?  Too short?  Why?",
	"What does your summer usually consist of?",
	"Who should be paid more, professional athletes or teachers?  Why or why not?",
	"What class do you enjoy the most and why?",
	"If you had only one month to live, what would you do?",
	"Describe your dream house.",
	"Who is your favorite person to be with?  Why?",
	"What would be your ideal job when you grow up?  Explain.",
	"If you could guest star on any TV show, what would it be and why?",
	"What do you think your life will be like in 10 years?  20 years?",
	"What is your definition of success?",
	"The saying goes, 'Money cannot buy happiness.'  Do you agree or disagree?  Why?",
	"What is the best day of the week?",
	"What are you most grateful for in your life?",
	"What do you like about yourself?",
	"How would your friends describe you?",
	"What is your favorite movie character?",
	"Which song inspires you the most?",
	"What do you do when you are feeling sad?",
	"What will you say if you met a dragon that can talk?",
	"Would you rather swim with dolphins or mermaid?",
	"What does your dream home look like?",
	"If you can build a treehouse what would it look like?",
	"If you can spend the weekend building something, what would you make?",
	"If you are given $5000, what will you do with that money?",
	"If you have to support a charity or a cause, which charity would you support? Why?",
	"What will you do if you win the lottery?",
	"What will you do if you are given the option to stay at home instead of going to school?",
	"Are you satisfied with your life right now?",
	"What would you like to change about your life?",
	"What is the best thing about your life?",
	"What is your biggest regret?",
	"What are you most grateful for in your life?",
	"What is your best childhood memory?",
	"What do you remember the most when you think of home?",
	"What is the best thing about growing up?",
	"If there is anything you can do right now, what would you do?",
	"If money was not a problem, how would live your life?",
	"Is there anything you imagine a lot as a child?",
	"What do you always wish for?",
	"What are your goals for next year?",
	"What has the pandemic thought you?",
	"Are friends more important or family?",
	"If you could turn back time, to which moment would you like to go back too?",
	"If you had $5000 to spend on yourself, how would you spend it?",
	"If you could be anything you want to be without being judged, who would you be?",
	"Is there anything you wished you had learned when you were younger?",
	"What advice would you give to your younger self?",
	"Is there a new skill you would like to learn?",
	"Is there any book that you would also re-read?",
	"What is the best advice you have ever received?",
	"What is the first thing you notice when you meet someone new?",
	"What are you most thankful for in your life?",
	"What is the one thing you wish you can do at some point in your life?",
	"What scares yours about dying?",
	"Do you think you are often misunderstood?",
	"If you can change one thing about the world, what would you change?",
	"Who is the biggest influencer in your life?",
	"Who do you admire the most in your life?",
	"Did you expect your life would be the way it is right now?",
	"What is the first thing you notice when you meet someone new?",
	"What are you most thankful for in your life?",
	"What is the one thing you wish you can do at some point in your life?",
	"What scares yours about dying?",
	"Do you think you are often misunderstood?",
	"If you can change one thing about the world, what would you change?",
	"Who is the biggest influencer in your life?",
	"Who do you admire the most in your life?",
	"Did you expect your life would be the way it is right now?",
	"Look at the room you sitting at right now, how does it make you feel?",
	"You woke up one day and found yourself in the opposite sex, what happens next?",
	"You have been voted as the leader of your country, what is the first thing you would do?",
	"Pick a country you have never visited, why would you move there?",
	"You are responsible to deliver food to people living on mars but you forgot your way there, what did you do next?",
	"You work as a spy in North Korea, what did you discover?",
	"You woke up one day and found yourself as one of the characters in a video game, describe what happens next?",
	"What advice do you often give people but never follow it yourself?",
	"What is your biggest achievement so far?",
	"What career line do you think is best for you?",
	"What motivated you to work towards your goals?",
	"Who had the worst influence on you?",
	"How do you imagine your life 10 years from now?",
	"What did you say Yes to today?",
	"Did you try something new recently?",
	"What does your dream life look like?",
	"What is your biggest strength?",
	"What is your best childhood memory?",
	"What are your weaknesses?",
	"What can you do to make the week ahead of a good one?",
	"How far are you from reaching your goals?",
	"What did you laugh about recently?",
	"Do you have empathy towards other people?",
	"What are the things people like best about you?",
	"What do you feel most uncomfortable doing?",
	"What are the things you need to work on in your life?",
	"What aspects of your life need more attention right now?",
	"What will you do if you are not afraid to be judged?",
	"What are you excited about in the future?",
	"What will you like to work in for the next few weeks?",
	"What do you enjoy doing the most?",
	"What are things you take granted for in your life?",
	"Name the people that would cheer you up when you are feeling down?",
	"What inspire you the most?",
	"What do you look forward to in your life?",
	"What skills are you grateful for in your life?",
	"What do you think gratitude means?",
	"What are the things about this year you are thankful for?",
	"What are the two thing in your life you are thankful for?",
	"When you look into the mirror, what do you see?",
	"Review your goals in the last 1 year and see how far you have made it.",
	"Describe the happiest place on earth",
	"What would you do if you will never fail?",
	"What would you do if money was not an issue?",
	"What will you let go of in life?",
	"What is a perfect day for you?",
	"Close your eyes and imagine what the perfect world looks like to you?",
	"What is the craziest dream you ever had?",
	"What are top 3 things you wish you can have in your life?",
	"When do you feel the world stop?",
	"What is your personal motto?",
	"What is the greatest gift you ever received?",
	"Are you an impulsive person or someone who prefers to “wait and see”?",
	"What irrationally annoys you more than anything else?",
	"What small thing can always bring you a bit of joy?",
	"What is your favorite thing to do on a lazy day?",
	"How often do you take risks?",
	"What is your favorite thing about being male or female?",
	"Who is your favorite president? What do you admire about him?",
	"How long do you think it will be before we see a female president?",
	"Do you think it's important to be a part of a community? Why or why not?",
	"What piece of modern technology are you most grateful to have?",
	"What would your life today be like without the Internet?",
	"Do you feel anonymous online? Why or why not?",
	"Do you prefer to binge-watch TV or keep up week-to-week? Why or why not?",
	"What is something you've always wanted to try but have never gotten around to?",
	"Can money buy happiness?",
	"If you could have a book with all the answers, would you read it? Why or why not?",
	"What goal are you working on right now?",
	"When do you feel most connected to other people?",
	"What is the greatest challenge you've ever faced?",
	"Writing Prompts for Daily Writing",
	"What is the most intense dream you've ever had?",
	"What is your favorite way to treat yourself after a long week?",
	"What are you exceptional at? Describe your talent.",
	"When do you feel most at peace?",
	"If you could create your own day of awareness, what would it be for?",
	"What would you put in a buried treasure chest?",
	"If you could rid the world of one problem, what would it be?",
	"What was the most exciting piece of news you ever received?",
	"Who knows you better than anyone else?",
	"How do you define success? Who is a successful person according to your definition?",
	"Are you the life of the party or someone who prefers to sit back and observe?",
	"What is the most interesting fact you know—and why does it interest you?",
	"Have you ever fallen in love?",
	"Do you follow current events? Why or why not?",
	"If you could have any one question answered, what would it be? How would the answer impact your life?",
	"What is the earliest lesson you remember learning from your parents?",
	"How do you define “family”?",
	"Do you believe in ghosts or spirits? Why or why not?",
	"How frequently do you exercise or engage in physical activity? Are you satisfied with your habits? Why or why not?",
	"Would you ever consider going to space? Why or why not?",
	"What is the most important thing you look for in a friend?",
	"What value do you hold most dear? Why?",
	"Choose three words to describe the current state of your life—and then explain why you chose them.",
	"Would you rather be rich, successful, healthy, or famous? Why?",
	"What do you think one of the hardest jobs in the world is? Would you ever consider doing it?",
	"Are you more scientific-minded or creative-minded? How does that affect your life?",
	"What kind of impact do commercials and advertising have on your life?",
	"Who inspires you? Why?",
	"What is something you are proud of?",
	"What would you do if you knew you could not fail?",
	"What is your ideal life? How can you achieve it?",
	"What is going well in your life right now?",
	"Describe in detail what you want your life to be like 5 years from now.",
	"If you had a million dollars, what would you spend it on and why?",
	"Are you living to your full potential? If not, why?",
	"What makes you feel the most confident?",
	"What was your biggest learning moment this week?",
	"What do you wish more people knew about you and why?",
	"What was your most embarrassing moment and why?",
	"If you could change anything about yourself what would it be and why?",
	"Describe your biggest accomplishment and why it means so much to you.",
	"How would you describe yourself to a stranger?",
	"If you could achieve anything in your life what would it be?",
	"What was the best thing that happened last week?",
	"If you could do anything you wanted to do today, what would it be?",
	"What fear would you like to overcome? What steps can you take to start overcoming it?",
	"What would you do if you did not have any fears?",
	"What is holding you back from going after the life you want?",
	"Get something off your chest. What is something you may be over-thinking?",
	"What are 10 things that always make you feel better, no matter what?",
	"Reply to your inner critic's opinions about your actions and decisions.",
	"What past challenge has turned out to be a blessing in disguise? Why?",
	"What makes you smile? What makes you happy?",
	"Imagine you have a touch of magic, and can make impossible things happen. What would you do?",
	"What does normal mean to you? Is it good or bad to be normal?",
	"What is one thing about today that surprised you?",
	"What is one mistake you made today and what did you learn from it?",
	"What are three things you're grateful for?",
	"If you could spend one day doing anything you want, what would you do?",
	"What is one thing that helps you when you're worried?",
	"What's one goal or challenge you have for yourself this week? How will you accomplish it?",
	"Think about your favorite hobby or activity. Why do you love it?",
	"What's one thing that always makes you laugh?",
	"Have you ever wanted to learn another language? What would you want to learn?",
	"What is the strangest thing you've ever learned in school?",
	"Would you rather it always be summer, spring, fall, or winter? Why?",
	"If you could tell your family one thing that's been on your mind lately, what would you say?",
	"Do you have any pets? What would you say to it if, one morning, it could suddenly talk?",
	"What's your favorite thing to do when you're outside?",
	"Think about one person who makes you feel loved. How do they show you that they care?",
	"Pretend that you had a time machine and could travel way into the future or to the past. Where would you go? What do you think life would be like?",
	"Do you have a favorite teacher? What are they like, and what's the best thing they've taught you?",
	"What's the funniest knock-knock joke you can think of?",
	"What is one interesting fact that you learned today?",
	"What do you think would be the coolest job to have? Why?",
	"Do you have a favorite book? Why is it your favorite?",
	"What do you want your life to be like when you're grown up?",
	"What's the best advice someone has ever given you?",
	"What would you do if you were the main character in your favorite fairy tale?",
	"What is your favorite thing about yourself? What's one thing you want to work on?",
	"Think about your favorite color. What does it remind you of?",
	"Who is someone you miss? What would you say to them if they were next to you right now?",
	"What's one thing you've never told anyone before?",
	"What do you love about your family?",
	"If you could talk to your future self, what would you ask?",
	"If you could talk to your past self, what would you say?",
	"What is one thing you're excited about? Why?",
	"If you could have any superpower, which one would you choose? What would you do with it?",
	"What's the best way to spend a rainy day?",
	"Pretend that you could either shrink down to the size of a mouse or grow as large as a building. What would you do and why?",
	"Think about a talent you wish that you had. What's one way that you can start practicing it?",
	"When you were little what did you want to be when you grew up, and did you follow through with your dream?",
	"What quote inspires you on tough days?",
	"If you could live anywhere in the world, where would you choose and why?",
	"If you won $1 million, what would you do with the money?",
	"What's the best advice you've ever been given?",
	"If you could have lunch with one person who is no longer here with us, who would you choose and what one question would you ask them?",
	"What's the biggest life lesson you've ever learned and how has it changed you?",
	"Describe something GOOD that happened to you today.",
	"What's the most embarrassing thing that's ever happened to you?",
	"What scares you?",
	"What are you most grateful for in your life?",
	"Describe your favorite time of year. What do you love about it, who do you spend it with, and what activities do you enjoy during that time?",
	"If you had $1,000 to spend on nobody but yourself, what would you buy and why?",
	"What is your favorite childhood memory?",
	"What qualities are important to you in a friendship/romantic relationship?",
	"Describe your dream job.",
	"What 3 things do you love most about yourself, and why?",
	"If you could travel to any destination in the world, where would you go and why?",
	"Describe a situation in which you helped someone else. What did you do? How did it make them feel? How did it make you feel?",
	"How would you describe yourself to a stranger?",
	"If you could change anything about yourself, what would it be and why?",
	"Describe a time in your life when you failed. What did you learn from it?",
	"What are your best character traits?",
	"What is something nobody knows about you? Why have you kept it a secret?",
	"What does your ideal life look like?",
	"What is your biggest fear, and what about it makes you feel scared?",
	"When something good or bad happens, who is the first person you want to tell, and why?",
	"What is your biggest regret in life, and if you could go back in time, what would you change about the situation?",
	"What quote or saying inspires you when you need it most?",
	"What inspires you?",
	"Who is your mentor, why do you look up to him/her, and what has he/she taught you?",
	"What is the biggest life lesson you've learned to date? Describe how the lesson was learned, and how it has impacted your life.",
	"What is the best piece of advice you've ever been given, and why did it have such an impact on you?",
	"If you could have an entire day to yourself with no responsibilities, who would you want to spend the day with and what would you choose to do together?",
	"What are your favorite family traditions?",
	"What makes you feel fulfilled?",
	"If you had five other lives to lead, what would you do in each of them?",
	"What would you do if you could travel into the past?",
	"If you could change one thing about the world, what would it be?",
	"What is the most valuable thing you have learned from this life?",
	"What does your happiest version look like to you?",
	"What do you do when people are negative and don't support you?",
	"How do you know when to let go?",
	"Your favorite quote that reminds you of your goals and dreams.",
	"Where do you see yourself in 5 years?",
	"What do you aspire to be?",
	"What does success mean to you?",
	"What is holding you back from living your dream life and accomplishing a goal?",
	"How is your life more positive today than it was a year ago?",
	"What makes you happy to be alive?",
	"What's an accomplishment you're proud of?",
	"What's one of your personality traits that you're grateful for?",
	"What do you love most about life?",
	"What do you love about yourself?",
	"What makes you unique?",
	"How do you show love to yourself on a daily basis?",
	"What is the biggest miracle of your life?",
	"Are you in the right path? If not, why not?",
	"Are you a truth seeker?",
	"What kind of world you want to live in?",
	"What does it mean to be free and fulfilled?",
	"Are you satisfied and content with your life?",
	"Why do most of us try to escape from the present moment?",
	"What do you think your spiritual gifts are?",
	"Are you the same person you were at the beginning of last year?",
]
