function generatePrompt() {
	randomIndex = Math.floor(Math.random() * prompts.length)
	return prompts[randomIndex]
}

module.exports = { generatePrompt }

const prompts = [
	"What is a challenge you faced this week and how did you overcome it?",
	"Describe a time when you felt truly proud of yourself. What happened and why did it make you feel that way?",
	"What is a goal you have for this semester and what steps are you taking to achieve it?",
	"Share a story about a time you helped a friend in need. How did it make you feel and what was the outcome?",
	"What is a book or article you recently read that had a significant impact on you? What was it about and why did it resonate with you?",
	"Think about a time when you had to make a difficult decision. What was the decision and what factors did you consider?",
	"Describe a moment when you felt out of your comfort zone. How did you handle the situation and what did you learn?",
	"What is a piece of advice you received that has stuck with you? Who gave it to you and why is it meaningful?",
	"Reflect on a time when you felt misunderstood. What happened and how did you resolve the situation?",
	"What is a skill you would like to develop and why? How do you plan to go about learning it?",
	"Share an experience where you learned something new about yourself. What was the situation and what did you discover?",
	"Think about a time when you had to work with someone very different from you. How did you manage the differences and what was the result?",
	"Describe a situation where you had to stand up for something you believed in. What was the issue and what was the outcome?",
	"What is a hobby or activity that brings you joy and why? How did you get started with it?",
	"Reflect on a time when you had to apologize to someone. What was the situation and how did you approach the apology?",
	"What is a tradition or custom that is important to you? Why is it significant and how do you participate in it?",
	"Share a story about a time you tried something new. What was it and how did it turn out?",
	"Think about a person who has had a positive influence on your life. Who are they and what impact have they had?",
	"Describe a time when you felt truly happy. What were you doing and who were you with?",
	"What is a cause or issue you are passionate about and why? How do you support it?",
	"Reflect on a time when you had to adapt to a new situation. What was the change and how did you handle it?",
	"What is a lesson you learned from a failure? How did it change your perspective or approach?",
	"Share a memorable experience from your childhood. What made it special and how does it affect you today?",
	"Think about a time when you had to rely on someone else. Who did you rely on and what was the outcome?",
	"Describe a moment when you felt inspired. What inspired you and how did it affect your actions?",
	"Reflect on a time when you had to give up something you wanted. What was it and why did you make that choice?",
	"What is a movie or show that you recently watched and enjoyed? What did you like about it and why?",
	"What is a skill you wish you had and why? How would it change your life?",
	"Think about a time when you had to forgive someone. What happened and how did you come to forgive them?",
	"Describe a place that holds special meaning to you. Why is it important and what memories do you associate with it?",
	"What is a misconception people have about you? How do you address it and what would you like people to know?",
	"Reflect on a time when you had to make a sacrifice. What did you give up and was it worth it?",
	"What is a song that has a special meaning to you? Why does it resonate with you and when do you listen to it?",
	"Share a story about a time you faced a fear. What was the fear and how did you confront it?",
	"Think about a time when you had to be patient. What was the situation and how did you manage your patience?",
	"Describe a moment when you felt truly connected to someone. What was the context and how did it make you feel?",
	"What is a memory you cherish and why? How does it influence your life today?",
	"Reflect on a time when you had to compromise. What was the situation and what was the result?",
	"What is a piece of art that you appreciate and why? How does it make you feel?",
	"Share a story about a time you learned from someone younger than you. What did they teach you and how did it impact you?",
	"Think about a time when you had to be resilient. What challenge did you face and how did you overcome it?",
	"Describe a situation where you felt grateful. What made you feel that way and how did you express your gratitude?",
	"What is a cultural experience that has impacted you? How did it influence your perspective or behavior?",
	"Reflect on a time when you had to be creative. What was the challenge and how did you come up with a solution?",
	"What is a tradition you would like to start and why? How would you go about implementing it?",
	"Share an experience where you had to manage your time effectively. What was the task and how did you succeed?",
	"Think about a time when you had to let go of something. What was it and how did you cope with the change?",
	"Describe a moment when you felt truly at peace. What were you doing and what contributed to that feeling?",
	"What is a dream you have for the future and why? How do you plan to achieve it?",
	"Reflect on a time when you had to ask for help. What was the situation and how did it turn out?",
	"What is a lesson you learned from someone older than you? How has it influenced your life?",
	"Share a story about a time you made a new friend. How did you meet and what brought you together?",
	"Think about a time when you had to deal with disappointment. What happened and how did you move forward?",
	"Describe a place you would like to visit and why. What attracts you to it and what would you like to do there?",
	"What is a personal achievement you are proud of and why? How did you accomplish it?",
	"Reflect on a time when you had to deal with conflict. What was the issue and how did you resolve it?",
	"What is a food that has special meaning to you? Why is it significant and when do you enjoy it?",
	"Share an experience where you had to be honest. What was the situation and what was the outcome?",
	"Think about a time when you had to learn something new. What was it and how did you approach the learning process?",
	"Describe a moment when you felt truly alive. What were you doing and what made it special?",
	"What is a value that is important to you and why? How do you live by it?",
	"Reflect on a time when you had to be flexible. What was the situation and how did you adapt?",
	"What is a tradition you would like to pass on to others and why? How do you plan to share it?",
	"Share a story about a time you felt misunderstood. What happened and how did you address the misunderstanding?",
	"Think about a time when you had to be resourceful. What challenge did you face and how did you overcome it?",
	"Describe a situation where you felt empowered. What contributed to that feeling and how did it affect your actions?",
	"What is a change you would like to see in the world and why? How do you think it can be achieved?",
	"Reflect on a time when you had to be patient with yourself. What was the situation and how did you manage it?",
	"What is a piece of music that inspires you and why? How does it influence your mood or actions?",
	"Share an experience where you had to be a good listener. What was the context and what did you learn?",
	"Think about a time when you had to deal with uncertainty. What was the situation and how did you navigate it?",
	"Describe a moment when you felt truly appreciated. What was the context and how did it make you feel?",
	"What is a lesson you learned from nature? How does it affect your perspective or behavior?",
	"Reflect on a time when you had to be courageous. What was the challenge and how did you face it?",
	"What is a tradition you have created for yourself and why? How do you practice it?",
	"Share a story about a time you felt hopeful. What was the situation and what gave you hope?",
	"Think about a time when you had to be independent. What was the situation and how did you handle it?",
	"Describe a place where you feel most at home. Why is it special and what memories do you associate with it?",
	"What is a lesson you learned from a mistake? How did it change your approach or perspective?",
	"Reflect on a time when you had to be forgiving. What was the situation and how did you come to forgive?",
	"What is a piece of advice you would give to your younger self and why? How would it have helped you?",
	"Share an experience where you had to take a risk. What was the risk and what was the outcome?",
	"Think about a time when you had to be compassionate. What was the situation and how did you show compassion?",
	"Describe a moment when you felt truly free. What were you doing and what contributed to that feeling?",
	"What is a lesson you learned from a friend? How has it influenced your life?",
	"Reflect on a time when you had to be persistent. What was the goal and how did you achieve it?",
	"What is a tradition you have participated in that was new to you? How did it affect you?",
	"Share a story about a time you felt challenged. What was the challenge and how did you overcome it?",
	"Think about a time when you had to be supportive. Who did you support and how did you help them?",
	"Describe a situation where you felt proud of someone else. What did they do and why did it make you proud?",
	"What is a lesson you learned from an experience outside your comfort zone? How did it change you?",
	"Reflect on a time when you had to be adaptable. What was the situation and how did you adjust?",
	"What is a piece of advice you would give to someone starting college and why? How would it benefit them?",
	"Share an experience where you had to be open-minded. What was the situation and what did you learn?",
	"Think about a time when you had to be responsible. What was the task and how did you manage it?",
	"Describe a moment when you felt truly content. What were you doing and what contributed to that feeling?",
	"What is a lesson you learned from a difficult situation? How did it change your perspective or actions?",
	"Reflect on a time when you had to be innovative. What was the challenge and how did you solve it?",
	"What is a tradition you would like to learn more about and why? How do you plan to explore it?",
	"Share a story about a time you felt motivated. What inspired you and how did it affect your actions?",
	"Think about a time when you had to be considerate. What was the situation and how did you show consideration?",
	"Describe a place you would like to explore and why. What interests you about it and what would you like to experience there?",
	"What is a lesson you learned from a relationship? How has it influenced your interactions with others?",
	"Reflect on a time when you had to be decisive. What was the decision and how did you make it?",
	"What is a piece of advice you would give to someone facing a challenge and why? How would it help them?",
	"Share an experience where you had to be empathetic. What was the situation and what did you learn?",
	"Think about a time when you had to be optimistic. What was the challenge and how did you maintain a positive outlook?",
]
